-- ============================================
-- setup-payouts-and-demotions.sql
-- Hand to Hand Fintech Loan Platform
-- Database Migration Script
-- ============================================

-- 1. Extend Profiles Table
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS demoted_at TIMESTAMPTZ;

-- 2. Create Payout Requests Table
CREATE TABLE IF NOT EXISTS public.payout_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  amount NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
  upi_id TEXT,
  account_name TEXT,
  account_no TEXT,
  bank_name TEXT,
  ifsc_code TEXT,
  status TEXT NOT NULL CHECK (status IN ('Pending', 'Paid')) DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  paid_at TIMESTAMPTZ
);

-- Enable RLS
ALTER TABLE public.payout_requests ENABLE ROW LEVEL SECURITY;

-- 3. Row Level Security Policies for Payout Requests

-- Policy 1: Agents can insert their own payout requests
DROP POLICY IF EXISTS "Agents can insert own payout requests" ON public.payout_requests;
CREATE POLICY "Agents can insert own payout requests"
  ON public.payout_requests FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = agent_id);

-- Policy 2: Agents can view their own payout requests
DROP POLICY IF EXISTS "Agents can view own payout requests" ON public.payout_requests;
CREATE POLICY "Agents can view own payout requests"
  ON public.payout_requests FOR SELECT
  TO authenticated
  USING (auth.uid() = agent_id);

-- Policy 3: Admin can manage all payout requests
DROP POLICY IF EXISTS "Admin can manage all payout requests" ON public.payout_requests;
CREATE POLICY "Admin can manage all payout requests"
  ON public.payout_requests FOR ALL
  TO authenticated
  USING (auth.jwt() ->> 'email' = 'handtohandloans@gmail.com');

-- 4. Adjust the existing handle_new_user function to parse phone numbers from metadata
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  v_role text;
  v_agent_code text;
  v_referrer_code text;
  v_approved boolean;
  v_phone text;
BEGIN
  -- Extract metadata
  v_role := COALESCE(new.raw_user_meta_data->>'role', 'user');
  v_referrer_code := new.raw_user_meta_data->>'referred_by';
  v_phone := new.raw_user_meta_data->>'phone';
  
  -- Set approval default: Users are automatically approved, Agents start unapproved
  IF v_role = 'agent' THEN
    v_approved := FALSE;
    -- Generate unique agent code H2H-XXXXX
    v_agent_code := 'H2H-' || floor(random() * 90000 + 10000)::text;
  ELSE
    v_approved := TRUE;
    v_agent_code := NULL;
  END IF;

  INSERT INTO public.profiles (id, full_name, email, role, agent_code, referred_by, approved, phone)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', ''),
    new.email,
    v_role,
    v_agent_code,
    v_referrer_code,
    v_approved,
    v_phone
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
