-- ============================================
-- setup-agent-portal.sql
-- Hand to Hand Fintech Loan Platform
-- Database Migration Script
-- ============================================

-- 1. Create Profiles Table (if not exists)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user', 'agent')),
  agent_code TEXT UNIQUE,
  referred_by TEXT,
  approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Applications Table (if not exists)
CREATE TABLE IF NOT EXISTS public.applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  client_name TEXT NOT NULL,
  client_mobile TEXT NOT NULL,
  bank_name TEXT NOT NULL,
  loan_amount NUMERIC(15, 2) NOT NULL,
  loan_type TEXT NOT NULL CHECK (loan_type IN ('PL', 'BL')),
  status TEXT NOT NULL CHECK (status IN ('Applied', 'In Progress', 'Approved', 'Disbursed', 'Rejected')) DEFAULT 'Applied',
  commission_rate NUMERIC(5, 2) DEFAULT 2.00, -- default 2% commission
  commission_amount NUMERIC(15, 2) DEFAULT 0.00,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  disbursed_at TIMESTAMPTZ
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

-- 3. Row Level Security Policies for profiles

-- Policy 1: Users can read their own profile
DROP POLICY IF EXISTS "Users can read own profile" ON public.profiles;
CREATE POLICY "Users can read own profile" 
  ON public.profiles FOR SELECT 
  TO authenticated 
  USING (auth.uid() = id);

-- Policy 2: Anyone can insert (needed during signup trigger)
DROP POLICY IF EXISTS "Allow system insert on profiles" ON public.profiles;
CREATE POLICY "Allow system insert on profiles"
  ON public.profiles FOR INSERT
  WITH CHECK (true);

-- Policy 3: Admin can read and update all profiles (for approvals)
DROP POLICY IF EXISTS "Admin can manage all profiles" ON public.profiles;
CREATE POLICY "Admin can manage all profiles"
  ON public.profiles FOR ALL
  TO authenticated
  USING (auth.jwt() ->> 'email' = 'utkrashtkumar@gmail.com');

-- 4. Row Level Security Policies for applications

-- Policy 1: Agents can insert their own client applications
DROP POLICY IF EXISTS "Agents can insert own applications" ON public.applications;
CREATE POLICY "Agents can insert own applications"
  ON public.applications FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = agent_id);

-- Policy 2: Agents can view their own client applications
DROP POLICY IF EXISTS "Agents can view own applications" ON public.applications;
CREATE POLICY "Agents can view own applications"
  ON public.applications FOR SELECT
  TO authenticated
  USING (auth.uid() = agent_id);

-- Policy 3: Admin can manage all client applications
DROP POLICY IF EXISTS "Admin can manage all applications" ON public.applications;
CREATE POLICY "Admin can manage all applications"
  ON public.applications FOR ALL
  TO authenticated
  USING (auth.jwt() ->> 'email' = 'utkrashtkumar@gmail.com');

-- 5. Automate Profile Creation on Auth Signup with Trigger

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  v_role text;
  v_agent_code text;
  v_referrer_code text;
  v_approved boolean;
BEGIN
  -- Extract metadata
  v_role := COALESCE(new.raw_user_meta_data->>'role', 'user');
  v_referrer_code := new.raw_user_meta_data->>'referred_by';
  
  -- Set approval default: Users are automatically approved, Agents start unapproved
  IF v_role = 'agent' THEN
    v_approved := FALSE;
    -- Generate unique agent code H2H-XXXXX
    v_agent_code := 'H2H-' || floor(random() * 90000 + 10000)::text;
  ELSE
    v_approved := TRUE;
    v_agent_code := NULL;
  END IF;

  INSERT INTO public.profiles (id, full_name, email, role, agent_code, referred_by, approved)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', ''),
    new.email,
    v_role,
    v_agent_code,
    v_referrer_code,
    v_approved
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Re-create Trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
